apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cert-manager-tls-push
  namespace: media
spec:
  updatePolicy: Replace
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - name: vaultwarden-webhook
      kind: ClusterSecretStore
  selector:
    secret:
      name: cert-manager-tls-secret
  data:
    - match:
        secretKey: tls.crt
        remoteRef:
          remoteKey: media/cert-manager-tls
          property: tls.crt
    - match:
        secretKey: tls.key
        remoteRef:
          remoteKey: media/cert-manager-tls
          property: tls.key
