{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vaultwarden-eso-bridge
  labels:
    app.kubernetes.io/name: vaultwarden-eso-bridge
    app.kubernetes.io/part-of: secrets-platform
    {{- with .Values.serviceMonitor.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden-eso-bridge
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval | default "30s" }}
      {{- with .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml . | indent 8 }}
      {{- end }}
  {{- with .Values.serviceMonitor.namespaceSelector }}
  namespaceSelector:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
