{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "vaultwarden-eso-bridge" .Values.serviceAccount.name }}
  labels:
    app.kubernetes.io/name: vaultwarden-eso-bridge
    app.kubernetes.io/part-of: secrets-platform
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
